added website of villages Adendorf and Scharnebeck
netzbegruenung/green-directory pull request #275
Opened 2020-12-19 21:47 UTC by kartenkarsten

2020-12-29 17:58 UTC, fbthb requested changes

2020-12-29 17:58 UTC, fbthb commented on data/countries/de/ni/lueneburg/data.yaml
>      url: https://gruene-lueneburg.de/home/ortsverbaende/scharnebeckadendorf/
I don't think it's a good idea to have two websites for one entry. Maybe it is better to overwrite the old one instead of adding a new one.
```suggestion
```

2020-12-31 11:12 UTC, fbthb approved these changes

2021-01-04 08:25 UTC, marians approved these changes

2021-01-04 08:26 UTC, marians commented
Once you update the branch, we can merge. Thanks!

2021-01-10 10:48 UTC, merged